### ISSUE TITLE
Conformance to Sendable

### ISSUE THREAD

**Issue by vdhamer** [pavolkmet/ScrollViewSectionKit#2]
The current version 15.4 of Xcode and [Swift 5.10](https://www.swift.org/blog/swift-5.10-released/), provides opt-in data-race checking for safe concurrency. The checking prevents data races by design.

If I install the code locally using "Clone using the web URL" and build the package (rather than the example app) using Xcode, I get a compiler warning:
```
Stored property 'base' of 'Sendable'-conforming struct 'AnyShapeBackport' has non-sendable type '(CGRect) -> Path'
```

Possibly Swift 6.0 may avoid this warning: Swift 5.10 has false positives that they want to get rid of in 6.0. See https://github.com/apple/swift-evolution/blob/main/proposals/0418-inferring-sendable-for-methods.md

**Comment by pavolkmet** [comment]
Hey @vdhamer thank you for bringing this up. In the new version 1.4.0 this is going to be resolved.

**Comment by vdhamer** [comment]
Thank you.
