### ISSUE TITLE
Section headers scroll off-screen

### ISSUE THREAD

**Issue by vdhamer** [pavolkmet/ScrollViewSectionKit#3]
Unlike sectioned List views with section headers, the section headers in these sectioned ScrollViews scroll offscreen.

This is not quite the same as ScrollView. It is an issue when you have a long list with say 10 sections with 20 rows per section: no convenient way to see where you are in this tree without scrolling upwards.

The ScrollViewSectionKit behaviour _is_ similar to say iOS Settings (e.g. Privacy and Security is split into Privacy/Security/Others) where the section headers do scroll.

**Comment by pavolkmet** [comment]
Hey @vdhamer, at the moment this library doesn't support this feature, I could look into it, but once again given the fact that iOS 17+ offers practically unlimited customization options this library is obsolete and you can do pretty much anything with the List or ScrollView components.
