### ISSUE TITLE
Does this work with `.scrollTargetBehavior(.viewAligned)` ?

### ISSUE THREAD

**Issue by vdhamer** [pavolkmet/ScrollViewSectionKit#4]
In the documentation, you might want to mention whether iOS 17 scrollview features are supported?

What I was looking for is the equivalent of a sectioned List (ok) but with smart scrolling as implemented in iOS 17.
I started to check this out, but then got distracted looking for non-scrolling (some call it "sticky") section headers...

**Comment by pavolkmet** [comment]
Hey @vdhamer, at the moment this library doesn't support `.scrollTargetBehavior(.viewAligned)`. Maybe in the future, I could look into it, but given the fact that iOS 17+ offers practically unlimited customization options this library is obsolete and you can do pretty much anything with the `List` or `ScrollView` components.
